Repository abhisek2004/Dev-Elevate, pull requests merged in 2025-10, with the labels that each got.

#547 feat(search): Add Search Results Page (/search)
  DevElevate/Client/src/App.tsx
  DevElevate/Client/src/components/Layout/SearchModal.tsx
  DevElevate/Client/src/pages/Search/SearchPage.tsx
  DevElevate/Client/src/utils/search.ts
  DevElevate/Server/index.js
Labels: gssoc25, Level-2

#556 feat(settings): Implement User Settings/Preferences Page
  DevElevate/Client/src/App.tsx
  DevElevate/Client/src/components/Layout/ProfileDropdown.tsx
  DevElevate/Client/src/components/Settings/AccountSettings.tsx
  DevElevate/Client/src/components/Settings/NotificationSettings.tsx
  DevElevate/Client/src/components/Settings/ProfileSettings.tsx
  DevElevate/Client/src/components/Settings/ThemeSettings.tsx
  DevElevate/Client/src/components/Settings/UserSettings.tsx
Labels: gssoc25, Level-3

#558 feat: Implement Animate on Scroll (AOS) & Fix Firebase Init 🚀
  DevElevate/Client/package-lock.json
  DevElevate/Client/package.json
  DevElevate/Client/src/App.tsx
  DevElevate/Client/src/components/Dashboard/DailyGoals.tsx
  DevElevate/Client/src/components/Dashboard/NewsWidget.tsx
  DevElevate/Client/src/components/Dashboard/ProgressWidget.tsx
  DevElevate/Client/src/components/Dashboard/QuickActions.tsx
  DevElevate/Client/src/components/Dashboard/StatsCards.tsx
  DevElevate/Client/src/components/Dashboard/StreakCalendar.tsx
  DevElevate/Client/src/components/Quiz/QuizHistory.tsx
  DevElevate/Client/src/pages/Landing/components/CTA.tsx
  DevElevate/Client/src/pages/Landing/components/CreatorPage.tsx
  DevElevate/Client/src/pages/Landing/components/FAQ.tsx
  DevElevate/Client/src/pages/Landing/components/Features.tsx
  DevElevate/Client/src/pages/Landing/components/Footer.tsx
  DevElevate/Client/src/pages/Landing/components/Hero.tsx
  DevElevate/Client/src/pages/Landing/components/Testimonials.tsx
  DevElevate/Client/src/pages/Notes/FallBackNotes.jsx
  DevElevate/Client/src/utils/firebase.ts
  package-lock.json
Labels: gssoc25, Level-1

#566 Implement search and AI summary for NotesPage
  DevElevate/Client/package-lock.json
  DevElevate/Client/package.json
  DevElevate/Client/src/App.tsx
  DevElevate/Client/src/pages/Notes/FallBackNotes.jsx
  DevElevate/Client/src/pages/Notes/NotesPage.jsx
  DevElevate/Client/src/utils/searchNotes.ts
  DevElevate/Client/src/utils/semanticSearch.js
Labels: gssoc25, Level-2, hacktoberfest 2025

#572 fix page scroll issue - 563
  DevElevate/Client/src/pages/Landing/components/Footer.tsx
Labels: gssoc25, Level-1, hacktoberfest 2025
