Repository abhisek2004/Dev-Elevate, pull requests merged in 2025-09, with the labels that each got.

#405 Implement user profile update and retrieval functionality; refactor a…
  DevElevate/Client/src/components/Auth/LoginRegister.tsx
  DevElevate/Client/src/components/Dashboard/Dashboard.tsx
  DevElevate/Client/src/components/Dashboard/NewsWidget.tsx
  DevElevate/Client/src/components/Profile/UserProfile.tsx
  DevElevate/Client/src/contexts/AuthContext.tsx
  DevElevate/Server/controller/userController.js
  DevElevate/Server/middleware/authMiddleware.js
  DevElevate/Server/model/UserModel.js
  DevElevate/Server/routes/userRoutes.js
Labels: gssoc25, Level-3

#407 feat(auth): Disable paste on registration password fields
  DevElevate/Client/src/components/Auth/LoginRegister.tsx
Labels: gssoc25, Level-2

#409 issue #251: **Fix and Integrate Real-Time Analytics in Admin Dashboard Overview**
  DevElevate/Client/src/App.tsx
  DevElevate/Client/src/components/AnalyticsDashboard.tsx
  DevElevate/Client/src/services/analyticsService.ts
  DevElevate/Server/controller/adminController.js
  DevElevate/Server/middleware/authMiddleware.js
  DevElevate/Server/package-lock.json
  DevElevate/Server/package.json
  DevElevate/Server/pdfServer.js
  DevElevate/Server/routes/adminRoutes.js
  DevElevate/Server/routes/analytics.js
Labels: gssoc25, Level-3

#420 fixed user payload console log
  DevElevate/Client/src/components/Auth/LoginRegister.tsx
Labels: gssoc25, Level-1

#423 fix: update import paths for User and AdminLog models in adminControl…
  DevElevate/Client/src/components/AnalyticsDashboard.tsx
  DevElevate/Server/controller/adminController.js
  DevElevate/Server/middleware/authMiddleware.js
Labels: gssoc25, Level-2

#451 Fix #435: Added global HTML sanitization middleware to prevent XSS
  DevElevate/Server/index.js
  DevElevate/Server/middleware/sanitizeMiddleware.js
  DevElevate/Server/package-lock.json
  DevElevate/Server/package.json
Labels: gssoc25, Level-2

#468 Refactor AdminSystemLogs and AnalyticsDashboard components for improv…
  DevElevate/Client/src/components/Admin/AdminSystemLogs.tsx
  DevElevate/Client/src/components/AnalyticsDashboard.tsx
  DevElevate/Server/controller/adminController.js
Labels: gssoc25, Level-3

#469 done Site Under Maintenance but some issue [like reload page then …
  DevElevate/Client/src/App.tsx
  DevElevate/Client/src/components/Admin/SystemSettings.tsx
  DevElevate/Client/src/components/Auth/ProtectedRoute.tsx
  DevElevate/Server/controller/systemController.js
  DevElevate/Server/controller/userController.js
  DevElevate/Server/index.js
  DevElevate/Server/middleware/authMiddleware.js
  DevElevate/Server/model/SystemSettings.js
  DevElevate/Server/routes/SystemSettingRoute.js
Labels: gssoc25, Level-3

#474 maintenanceMode done
  DevElevate/Client/src/components/Auth/ProtectedRoute.tsx
  DevElevate/Client/src/components/Layout/ProfileDropdown.tsx
Labels: gssoc25, Level-2

#482 remove extra components in app.txs
  DevElevate/Client/src/App.tsx
  DevElevate/Client/src/components/Chatbot/Chatbot.tsx
  DevElevate/Client/src/components/Layout/Layout.tsx
Labels: gssoc25, Level-3

#485 <Route path="/" element={<LandingPage />} />
  DevElevate/Client/src/App.tsx
Labels: gssoc25, Level-1

#487 Add Helmet & HPP middleware for security (#477)
  DevElevate/Server/config/rateLimiting.js
  DevElevate/Server/index.js
  DevElevate/Server/middleware/rateLimiting/createLimiter.js
  DevElevate/Server/middleware/rateLimiting/index.js
  DevElevate/Server/middleware/security.js
  DevElevate/Server/package-lock.json
  DevElevate/Server/package.json
Labels: gssoc25, Level-3

#488 Refactor routing and component props in AppContent; update Navbar and…
  DevElevate/Client/src/App.tsx
  DevElevate/Client/src/components/Layout/Navbar.tsx
  DevElevate/Client/src/components/Profile/UserProfile.tsx
  DevElevate/Client/src/components/Quiz/QuizHistory.tsx
Labels: gssoc25, Level-2

#490 feat: Add Graphing Calculator, Physics Tools, Scientific Calculator, …
  DevElevate/Client/package-lock.json
  DevElevate/Client/package.json
  DevElevate/Client/src/components/Calculator/MainCalculator.tsx
  DevElevate/Client/src/components/Calculator/modes/BasicCalculator.tsx
  DevElevate/Client/src/components/Calculator/modes/FinancialCalculator.tsx
  DevElevate/Client/src/components/Calculator/modes/GraphingCalculator.tsx
  DevElevate/Client/src/components/Calculator/modes/PhysicsTools.tsx
  DevElevate/Client/src/components/Calculator/modes/ScientificCalculator.tsx
  DevElevate/Client/src/components/Calculator/modes/UnitConverter.tsx
  DevElevate/Client/src/components/Layout/Navbar.tsx
  DevElevate/Client/src/contexts/AuthContext.tsx
  DevElevate/Client/src/contexts/CalculatorHistoryContext.tsx
Labels: gssoc25, Level-3

#491 Ui changes
  DevElevate/Client/src/App.tsx
  DevElevate/Client/src/components/Layout/Footer.tsx
  DevElevate/Client/src/components/Layout/Navbar.tsx
  DevElevate/Client/src/pages/Landing/components/ApiDocs.tsx
  DevElevate/Client/src/pages/Landing/components/CTA.tsx
  DevElevate/Client/src/pages/Landing/components/CreatorPage.tsx
  DevElevate/Client/src/pages/Landing/components/Disclaimer copy.tsx
  DevElevate/Client/src/pages/Landing/components/Disclaimer.tsx
  DevElevate/Client/src/pages/Landing/components/DocumentationPage.tsx
  DevElevate/Client/src/pages/Landing/components/PrivacyPolicy copy.tsx
  DevElevate/Client/src/pages/Landing/components/PrivacyPolicy.tsx
  DevElevate/Client/src/pages/Landing/components/TermsOfService copy.tsx
  DevElevate/Client/src/pages/Landing/components/TermsOfService.tsx
Labels: gssoc25, Level-3

#492 Contests Module Implementation (LeetCode-style)
  DevElevate/Client/package-lock.json
  DevElevate/Client/package.json
  DevElevate/Client/src/App.tsx
  DevElevate/Client/src/components/Profile/UserProfile.tsx
  DevElevate/Client/src/contexts/SocketContext.tsx
  DevElevate/Client/src/pages/Coding/Coding.tsx
  DevElevate/Client/src/pages/Coding/Components/CodeEditor/CodeEditor.tsx
  DevElevate/Client/src/pages/Coding/Components/ContestCard.tsx
  DevElevate/Client/src/pages/Coding/Components/Leaderboard/ContestLeaderboard.tsx
  DevElevate/Client/src/pages/Coding/Components/ProblemDetail/ProblemDescription.tsx
  DevElevate/Client/src/pages/Coding/Pages/ContestDetailsPage.tsx
  DevElevate/Client/src/pages/Coding/Pages/ContestProblemPage.tsx
  DevElevate/Client/src/pages/Coding/Pages/ContestResultsPage.tsx
  DevElevate/Client/src/pages/Coding/Pages/ContestsPage.tsx
  DevElevate/Client/src/pages/Coding/Types/index.ts
  DevElevate/Server/controller/contestController.js
  DevElevate/Server/index.js
  DevElevate/Server/model/Contest.js
  DevElevate/Server/model/ContestSubmission.js
  DevElevate/Server/model/Problem.js
  DevElevate/Server/model/UserModel.js
  DevElevate/Server/package-lock.json
  DevElevate/Server/package.json
  DevElevate/Server/routes/contestRoutes.js
  DevElevate/Server/socket.js
  DevElevate/Server/utils/ratingCalculator.js
Labels: gssoc25, Level-3

#493 Add notes section in the project
  DevElevate/Client/package-lock.json
  DevElevate/Client/package.json
  DevElevate/Client/src/App.tsx
  DevElevate/Client/src/components/Layout/Breadcrumb.jsx
  DevElevate/Client/src/components/notes/NotesView.tsx
  DevElevate/Client/src/hooks/useMobile.js
  DevElevate/Client/src/pages/Notes/FallBackNotes.jsx
  DevElevate/Client/src/pages/Notes/GitVersionControl/GitNotes.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JavaScriptFundamentals.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Dom_Bom/JsDocumentObject.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Dom_Bom/JsGetElementById.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Dom_Bom/JsGetElementsByClassName.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Dom_Bom/JsGetElementsByName.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Dom_Bom/JsGetElementsByTagName.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Dom_Bom/JsHistoryObject.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Dom_Bom/JsInnerHTML.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Dom_Bom/JsNavigatorObject.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Dom_Bom/JsOuterHTML.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Dom_Bom/JsScreenObject.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Dom_Bom/JsWindowObject.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Introduction/JsExecution.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Introduction/JsIntroduction.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Introduction/NodeJsInstallation.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsBasics/ForLoops.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsBasics/Functions.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsBasics/IfElseConditionals.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsBasics/IfElseLadder.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsBasics/SwitchCase.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsBasics/TernaryOperator.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsBasics/WhileLoops.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/ArraysAndMethods.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/BooleanInJS.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/DateInJS.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/LoopsWithArrays.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/MapFilterReduce.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/MathInJS.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/NumberInJS.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsObjects/StringsInJS.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsVariables/OperatorsAndExpressions.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsVariables/PrimitivesAndObjects.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsVariables/VarLetConst.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsVariables/VariableNamingRules.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/JsVariables/WhatAreVariables.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Oops/JsAbstraction.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Oops/JsClass.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Oops/JsConstructor.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Oops/JsEncapsulation.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Oops/JsInheritance.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Oops/JsObjects.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Oops/JsPolymorphism.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/JsTopics/Oops/JsStaticMethod.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/components/CodeBlock.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/components/JavaScriptNotesSideBar.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/components/JsHeroPage.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/components/JsPageTitleManager.jsx
  DevElevate/Client/src/pages/Notes/JavaScriptFundamentals/components/JsSideBarData.json
  DevElevate/Client/src/pages/Notes/NotesData.js
  DevElevate/Client/src/pages/Notes/NotesPage.jsx
  DevElevate/Client/src/pages/Notes/PythonBasics/PythonNotes.jsx
  DevElevate/Client/src/pages/Notes/ReactPatterns/ReactPattern.jsx
Labels: gssoc25, Level-3

#496 fix: Adjust animation duration for loading dots in SplashScreen compo…
  DevElevate/Client/src/components/Layout/SplashScreen.tsx
Labels: gssoc25, Level-1

#501 Added documentation
  .github/ISSUE_TEMPLATE/documentation.md
Labels: gssoc25, Level-1

#508 Add pull request template for contributions
  .github/pull_request_template.md
Labels: gssoc25, Level-1

#517 Fix the constantly failing PR
  .github/workflows/pr-comment.yml
Labels: gssoc25, Level-1

#519 Optimized adminController.js for efficiency and maintainability
  DevElevate/Server/controller/adminController.js
Labels: gssoc25, Level-2

#525 Add Advanced Analytics Dashboard with CSV Export Feature
  DevElevate/Client/package-lock.json
  DevElevate/Client/package.json
  DevElevate/Client/src/components/AnalyticsDashboard.tsx
  DevElevate/Server/routes/analytics.js
Labels: gssoc25, Level-3
